# Site settings
title: Conf. Choir stalls and workshops.
subtitle: Greifswald, June 23–26, 2016
email: seligera@cms.hu-berlin.de
description: > # this means to ignore newlines until "baseurl:"
  TBA
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.chorgestuehle-und-ihre-werkstaetten.bwg.hu-berlin.de/en.html"
port: 80

# Build settings
markdown: kramdown

kramdown:
  auto_ids: false

exclude:
  - '*.orig'
